### ISSUE TITLE
Manual Verification

### ISSUE THREAD

**Issue by deatttthhh** [ewang20027/ZeroRaidBot#3]
Manual Verification modules for those who get filtered out for not meeting certain requirements.
To that a way to hid verification requirements.
Also a command to manually verify a user if everything else fails.

**Comment by ewang20027** [comment]
Manual verification will be triggered if the person fails to meet one or more requirement(s) defined by the server (EXCEPTION -- blacklisted ppl will be told who blacklisted them and why so they can appeal) AND the manual verification channel is defined.

**Comment by ewang20027** [comment]
Completed.
